services:
  gateway_service:
    build:
      context: gateway_service
    environment: &gateway-environment
      FLIGHT_SERVICE_HOST: ${FLIGHT_SERVICE_HOST}
      TICKET_SERVICE_HOST: ${TICKET_SERVICE_HOST}
      BONUS_SERVICE_HOST: ${BONUS_SERVICE_HOST}
      RABBITMQ_URL: ${RABBITMQ_URL}
    ports:
      - 8080:8080
    depends_on:
      flight_service:
        condition: service_started
      ticket_service:
        condition: service_started
      bonus_service:
        condition: service_started
      rabbitmq:
        condition: service_started

  purchase_worker:
    build:
      context: gateway_service
    command: ["python", "rabbit.py"]
    restart: on-failure
    environment: *gateway-environment
    depends_on:
      rabbitmq:
        condition: service_started

  flight_service:
    build:
      context: flight_service
    environment:
      FLIGHT_SERVICE_DB_PROTOCOL: ${FLIGHT_SERVICE_DB_PROTOCOL}
      FLIGHT_SERVICE_DB_USER: ${FLIGHT_SERVICE_DB_USER}
      FLIGHT_SERVICE_DB_PASSWORD: ${FLIGHT_SERVICE_DB_PASSWORD}
      FLIGHT_SERVICE_DB_HOST: postgres
      FLIGHT_SERVICE_DB_PORT: ${FLIGHT_SERVICE_DB_PORT}
      FLIGHT_SERVICE_DB_NAME: ${FLIGHT_SERVICE_DB_NAME}
    ports:
      - 8060:8060
    depends_on:
      postgres:
        condition: service_started

  ticket_service:
    build:
      context: ticket_service
    environment:
      TICKET_SERVICE_DB_PROTOCOL: ${TICKET_SERVICE_DB_PROTOCOL}
      TICKET_SERVICE_DB_USER: ${TICKET_SERVICE_DB_USER}
      TICKET_SERVICE_DB_PASSWORD: ${TICKET_SERVICE_DB_PASSWORD}
      TICKET_SERVICE_DB_HOST: postgres
      TICKET_SERVICE_DB_PORT: ${TICKET_SERVICE_DB_PORT}
      TICKET_SERVICE_DB_NAME: ${TICKET_SERVICE_DB_NAME}
    ports:
      - 8070:8070
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_started

  bonus_service:
    build:
      context: bonus_service
    environment:
      BONUS_SERVICE_DB_PROTOCOL: ${BONUS_SERVICE_DB_PROTOCOL}
      BONUS_SERVICE_DB_USER: ${BONUS_SERVICE_DB_USER}
      BONUS_SERVICE_DB_PASSWORD: ${BONUS_SERVICE_DB_PASSWORD}
      BONUS_SERVICE_DB_HOST: postgres
      BONUS_SERVICE_DB_PORT: ${BONUS_SERVICE_DB_PORT}
      BONUS_SERVICE_DB_NAME: ${BONUS_SERVICE_DB_NAME}
    ports:
      - 8050:8050
    depends_on:
      postgres:
        condition: service_started

  postgres:
    image: postgres:18
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql
      - ./postgres/:/docker-entrypoint-initdb.d/
    expose:
      - 5432

  rabbitmq:
    image: rabbitmq:management
    restart: on-failure
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
    volumes:
      - q-data:/var/lib/rabbitmq
    expose:
      - 5672
    ports:
      - 15672:15672

volumes:
  db-data:
  q-data:
